"""empty message

Revision ID: 8b78c9a21f16
Revises: 71a7d45a9768
Create Date: 2020-06-03 11:48:33.302588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b78c9a21f16'
down_revision = '71a7d45a9768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("category") as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50)))
        batch_op.drop_column('category_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_name', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('category', 'name')
    # ### end Alembic commands ###
