"""empty message

Revision ID: b8cfc218f15d
Revises: 82627074a87d
Create Date: 2020-06-20 22:57:30.080692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8cfc218f15d'
down_revision = '82627074a87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("category") as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'count')
    # ### end Alembic commands ###
